<?php

namespace Tableless\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
	private function getQueryBuilder()
	{
		$em = $this->getEntityManager();

		$queryBuilder = $em->getRepository('TablelessModelBundle:Post')
						   ->createQueryBuilder('p');

		return $queryBuilder;
	}

	public function findAllInOrder()
	{
	    $qb = $this->getQueryBuilder()
	    		   ->orderBy('p.createdAt', 'desc');
	 
	    return $qb->getQuery()->getResult();
	}

}
